name: Docker Image CI

###
# This would be the ideal workflow, but it doesn't work.
# docker/setup-buildx-action@v2 is not able to reliably
# build images for ghcr.io
# Keeping this around for a future fix -
# Pinning buildkit works *sometimes*
###
on: workflow_dispatch
    
env:
  UBUNTU_VERSION: 22.04
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  ubuntu-base:
    runs-on: ubuntu-latest
    steps:
      -
        name: Env Setter
        run: |
          echo "PACKAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
          echo "TAG=ubuntu-${{ env.UBUNTU_VERSION }}" >> ${GITHUB_ENV}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        ## Attempt to solve ghcr build failures https://github.com/docker/build-push-action/issues/761 - 0.12.0 does not fix.
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: build
          build-args: |
            IMAGE_BASE=ubuntu:${{ env.UBUNTU_VERSION }}
            XPU_TARGET=CPU
          push: true
          # Avoids unknown/unknown architecture and extra metadata
          provenance: false
          #cache-from: type=gha,scope=${{ github.ref_name }}-${{ env.TAG }}
          #cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-${{ env.TAG }}
          tags: |
            ghcr.io/${{ env.PACKAGE_NAME }}:${{ env.TAG }}
    
  nvidia-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cuda:
          - 11.8.0
          - 12.1.0
          - 12.2.0
        level:
          - "base"
          - "runtime"
          - "devel"
          - "cudnn8-runtime"
          - "cudnn8-devel"
        exclude:
          - cuda: 12.2.0
            level: "cudnn8-runtime" # Not yet available
          - cuda: 12.2.0
            level: "cudnn8-devel" # Not yet available
    steps:
      -
        name: Env Setter
        run: |
          echo "PACKAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
          echo "TAG=cuda-${{ matrix.cuda }}-${{ matrix.level }}-${{ env.UBUNTU_VERSION }}" >> ${GITHUB_ENV}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        ## Attempt to solve ghcr build failures https://github.com/docker/build-push-action/issues/761 - 0.12.0 does not fix.
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: build
          build-args: |
            IMAGE_BASE=nvidia/cuda:${{ matrix.cuda }}-${{ matrix.level }}-ubuntu${{ env.UBUNTU_VERSION }}
            XPU_TARGET=NVIDIA_GPU
            CUDA_VERSION=${{ matrix.cuda }}
            CUDA_LEVEL=${{ matrix.level }}
          push: true
          provenance: false
          #cache-from: type=gha,scope=${{ github.ref_name }}-${{ env.TAG }}
          #cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-${{ env.TAG }}
          tags: |
            ghcr.io/${{ env.PACKAGE_NAME }}:${{ env.TAG }}

  amd-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rocm:
          - 5.4.1
        level:
          - "core"
          - "runtime"
          - "devel"
    steps:
      -
        name: Env Setter
        run: |
          echo "PACKAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
          echo "TAG=rocm-${{ matrix.rocm }}-${{ matrix.level }}-${{ env.UBUNTU_VERSION }}" >> ${GITHUB_ENV}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        ## Attempt to solve ghcr build failures https://github.com/docker/build-push-action/issues/761 - 0.12.0 does not fix.
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: build
          build-args: |
            IMAGE_BASE=ubuntu:${{ env.UBUNTU_VERSION }}
            XPU_TARGET=AMD_GPU
            ROCM_VERSION=${{ matrix.rocm }}
            ROCM_LEVEL=${{ matrix.level }}
          push: true
          provenance: false
          #cache-from: type=gha,scope=${{ github.ref_name }}-${{ env.TAG }}
          #cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-${{ env.TAG }}
          tags: |
            ghcr.io/${{ env.PACKAGE_NAME }}:${{ env.TAG }}